const express = require('express');
const router = express.Router();
const AdminController = require('../controller/admin');
const UserController = require('../controller/student');
const {verifyTokenAdmin} = require('../middleware/verifyToken');
router.get('/show-users', verifyTokenAdmin, AdminController.showAllUser);
router.post('/create-class', verifyTokenAdmin, AdminController.CreateClass);
router.post('/create-test', verifyTokenAdmin, AdminController.CreateTest);
router.post(`/:test_slug/create-question`, verifyTokenAdmin, AdminController.CreateQuestion);
router.post(`/:slug/add-test`, verifyTokenAdmin, AdminController.AddTestToClass);
router.post(`/add-test-student`, verifyTokenAdmin, AdminController.addTestToUser);
router.put(`/:test_slug/active-test`, verifyTokenAdmin, AdminController.UpdateTesr);
router.get('/all-class', verifyTokenAdmin,UserController.ShowClass);
module.exports = router;